### ISSUE TITLE
[BUG] Pathoplexus website strangely not showing up (for me) when googling `pathoplexus`

### ISSUE THREAD

**Issue by corneliusroemer** [pathoplexus/pathoplexus#106]
When googling `pathoplexus` I _don't_ get any results for pathoplexus.org strangely

<img width="1131" alt="Google Chrome 2024-09-05 13 35 21" src="https://github.com/user-attachments/assets/cb1d9778-c867-48bc-9a9f-66742f317a62">

Can others try to reproduce? I tried both incognito and non-incognito: https://www.google.com/search?q=pathoplexus&oq=pathoplexus

**Comment by corneliusroemer** [comment]
@theosanderson sees it as first result, Emma can reproduce. So likely a Google issue, maybe Switzerland specific. Let's recheck in a day. I've gone through search console and there is nothing explaining my observations.

**Comment by theosanderson** [comment]
Reported as resolved
