### ISSUE TITLE
[BUG] CI link-checker is flaky

### ISSUE THREAD

**Issue by anna-parker** [pathoplexus/pathoplexus#152]
**Describe the bug**
Our link checker test keeps failing with timeouts: 
<img width="719" alt="image" src="https://github.com/user-attachments/assets/7bbba16a-2199-4e46-8d2f-b7e4726d397a">

Lets see if we can increase timeout in the config somewhere

**Comment by corneliusroemer** [comment]
Thanks for investigating!

Let's keep track of which URLs time out - if it's external ones we can simply filter them out using regex.

Please add any that time out to this issue and I'll fix it.

Also, links to the action/step that failed would be great to include in the issue 🙏

**Comment by corneliusroemer** [comment]
I think I've mostly deflaked it now - reopen if the issue is back.
