### ISSUE TITLE
[BUG] Broken link checker wrongly reports errors for links with anchor

### ISSUE THREAD

**Issue by chaoran-chen** [pathoplexus/pathoplexus#165]
[Here](https://github.com/pathoplexus/pathoplexus/actions/runs/11022387713/job/30611831355), the broken link checker reports the following two links as not found although they work:

- https://backend.pathoplexus.org/swagger-ui/index.html#/submission-controller/submit
- https://backend.pathoplexus.org/swagger-ui/index.html#/submission-controller

<img width="1063" alt="image" src="https://github.com/user-attachments/assets/64b89f8b-387c-4bce-a1e5-8dba8b952da0">

**Comment by corneliusroemer** [comment]
Swagger doesn't seem to create the ids in the static HTML output, which seems like a swagger bug but we can work around this by disabling those.fragment checks
