### ISSUE TITLE
[BUG] Accidental git submodule

### ISSUE THREAD

**Issue by theosanderson** [pathoplexus/pathoplexus#80]
Currently this repo contains the `loculus_repo` as a git submodule. This gets added by the GitHub action I added to create PRs to update the Loculus version. It's not actually needed for that and not intended. But it also doesn't do much harm. We can fix this at some point.

**Comment by corneliusroemer** [comment]
I noticed and wondered, thanks for explaining. Should we just remove it before committing in the action?

**Comment by theosanderson** [comment]
SGTM!
